### ISSUE TITLE
No way to validate against custom $schema's

### ISSUE THREAD

**Issue by dmakovec** [mozilla-services/react-jsonschema-form#783]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

There doesn't seem to be a way to set up validation against custom schemata. 

For documents which use a $schema URI other than "http://json-schema.org/draft-06/schema#" or similar, it's necessary to call Ajv's addSchema() method to pre-load the schema for validation against. There doesn't seem to be a way to do that at present?

### Steps to Reproduce
Use a document with a custom $schema, e.g.

```
{
    "$schema": "https://my.example.site/schema#",
    "title": "Product",
    "description": "A product from Acme's catalog",
    "type": "object",
   ...
}
```

#### Expected behavior

Form is validated against that schema.

#### Actual behavior

```
JsonSchemaFormWrapper.js:166
Error: no schema with key or ref "https://my.example.site/schema"
ajv.js:95
    at Ajv.validate (/home/user/project/node_modules/ajv/lib/ajv.js:95:1)

    at Ajv.validateSchema (/home/user/project/node_modules/ajv/lib/ajv.js:179:8)

    at Ajv._addSchema (/home/user/project/node_modules/ajv/lib/ajv.js:311:1)

    at Ajv.validate (/home/user/project/node_modules/ajv/lib/ajv.js:97:1)

    at validateFormData (/home/user/project/node_modules/react-jsonschema-form/lib/validate.js:196:1)

    at Form.validate (/home/user/project/node_modules/react-jsonschema-form/lib/components/Form.js:166:1)

    at eval (/home/user/project/node_modules/react-jsonschema-form/lib/components/Form.js:87:1)

    at Form._this.onSubmit (/home/user/project/node_modules/react-jsonschema-form/lib/components/Form.js:103:10)

    at HTMLUnknownElement.callCallback (/home/user/project/node_modules/react-dom/cjs/react-dom.development.js:540:1)
....
```

### Version

1.0.0

**Comment by handrews** [comment]
Hi folks- I'm dropping in from the JSON Schema spec team.

In the forthcoming draft-08, we will be adding features to make recognizing and working with custom meta-schemas (as indicated by `$schema` easier.  We would welcome feedback on these proposals, starting with json-schema-org/json-schema-spec#561, and then json-schema-org/json-schema-spec#563 and json-schema-org/json-schema-spec#564

Incidentally, this would make it easy to model UI-related keywords as a JSON Schema vocabulary.

**Comment by epicfaace** [comment]
I'm merging this issue into #794.
